server:
  port: ${PORT}

spring:
  application:
    name: ${APPLICATION_NAME}

  datasource:
    url: jdbc:postgresql://${POSTGRES_DB}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: FULL
  hystrix:
    enabled: false

logging:
  level:
    pt.ulusofona.cd.store.shared.client: DEBUG
    feign: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html